name : "cv-en"

replicaCount: 2

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 81

containerPort: 81

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  path: /
  port: 81
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /
  port: 81
  initialDelaySeconds: 5
  periodSeconds: 10
